AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.


Parameters:
  Project:
    Type: String
    Description: This is the tag of the project
  Application:
    Type: String
    Description: This is the tag of the application
  BucketName:
    Type: String
    Description: Name of the S3 bucket to grant read-only access to
  LambdaFunctionZipFileKey:
    Type: String
    Description: Name of the S3 bucket to grant read-only access to
  rabbitBroker:
    Type: String
    Description: Rabbit Broker HTTPS url
  rabbitDefS3Key:
    Type: String
    Description: s3 key of the rabbit config definition to upload
  rabbitPass:
    Type: String
    Description: rabbit admin password
  rabbitUser:
    Type: String
    Description: rabbit admin username


Resources:
  LambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: S3ReadOnlyAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - Fn::Sub: arn:aws:s3:::${BucketName}
                  - Fn::Sub: arn:aws:s3:::${BucketName}/*
      Tags:
        - Key: Project
          Value: !Sub '${Project}'
        - Key: Application
          Value: !Sub '${Application}'
        - Key: Name
          Value: !Sub '${Project}-${Application}'


  updaterabbitmqdefinition:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: updaterabbitmqdefinition
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref LambdaFunctionZipFileKey
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt LambdaServiceRole.Arn
      Environment:
        Variables:
          configBucket: !Ref BucketName
          rabbitBroker: !Ref rabbitBroker
          rabbitDefS3Key: !Ref rabbitDefS3Key
          rabbitPass: !Ref rabbitPass
          rabbitUser: !Ref rabbitUser
      Tags:
        - Key: Project
          Value: !Sub '${Project}'
        - Key: Application
          Value: !Sub '${Application}'
        - Key: Name
          Value: !Sub '${Project}-${Application}'

